USE INF2025i_AppleMusicLight;

-- 1. RECORDLABEL
LOAD DATA INFILE 'C:/Daten/CSV/RECORDLABEL.csv'
    INTO TABLE RECORDLABEL
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

-- 2. USER
LOAD DATA INFILE 'C:/Daten/CSV/USER.csv'
    INTO TABLE USER
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

-- 3. ARTIST
LOAD DATA INFILE 'C:/Daten/CSV/ARTIST.csv'
    INTO TABLE ARTIST
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

-- 4. ALBUM
LOAD DATA INFILE 'C:/Daten/CSV/ALBUM.csv'
    INTO TABLE ALBUM
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

-- 5. TRACK
LOAD DATA INFILE 'C:/Daten/CSV/TRACK.csv'
    INTO TABLE TRACK
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

-- 6. TRACK_FEATURE
LOAD DATA INFILE 'C:/Daten/CSV/TRACK_FEATURE.csv'
    INTO TABLE TRACK_FEATURE
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

-- 7. STREAM_EREIGNIS
LOAD DATA INFILE 'C:/Daten/CSV/STREAM_EREIGNIS.csv'
    INTO TABLE STREAM_EREIGNIS
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;