USE INF2025i_AppleMusicLight;

-- 1. RECORDLABEL
LOAD DATA INFILE '/Users/sonoma/GitHub/Modul-164/LB2/RECORDLABEL.csv'
    INTO TABLE RECORDLABEL
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

-- 2. USER
LOAD DATA INFILE '/Users/sonoma/GitHub/Modul-164/LB2/USER.csv'
    INTO TABLE USER
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

-- 3. ARTIST
LOAD DATA INFILE '/Users/sonoma/GitHub/Modul-164/LB2/ARTIST.csv'
    INTO TABLE ARTIST
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

-- 4. ALBUM
LOAD DATA INFILE '/Users/sonoma/GitHub/Modul-164/LB2/ALBUM.csv'
    INTO TABLE ALBUM
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS
    (ID, ArtistID, Titel, Erscheinungsdatum, Genre);

-- 5. TRACK
LOAD DATA INFILE '/Users/sonoma/GitHub/Modul-164/LB2/TRACK.csv'
    INTO TABLE TRACK
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

-- 6. TRACK_FEATURE
LOAD DATA INFILE '/Users/sonoma/GitHub/Modul-164/LB2/TRACK_FEATURE.csv'
    INTO TABLE TRACK_FEATURE
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

-- 7. STREAM_EREIGNIS
LOAD DATA INFILE '/Users/sonoma/GitHub/Modul-164/LB2/STREAM_EREIGNIS.csv'
    INTO TABLE STREAM_EREIGNIS
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

