CREATE DATABASE IF NOT EXISTS INF2025i_AppleMusicLight;
USE INF2025i_AppleMusicLight;

CREATE TABLE USER (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Benutzername VARCHAR(20) NOT NULL UNIQUE,
    Emailadresse VARCHAR(100) NOT NULL UNIQUE,
    Registrierungsdatum DATE NOT NULL DEFAULT CURRENT_DATE,
    HatPremium BOOLEAN NOT NULL
);

CREATE TABLE RECORDLABEL (
    LabelID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    LandCode VARCHAR(2) NOT NULL DEFAULT 'CH'
);

CREATE TABLE ARTIST (
    ArtistID INT AUTO_INCREMENT PRIMARY KEY,
    LabelID INT,
    Kuenstlername VARCHAR(100) NOT NULL,
    Biografie TEXT,
    FOREIGN KEY (LabelID) REFERENCES RECORDLABEL(LabelID) ON DELETE NO ACTION
);

CREATE TABLE ALBUM (
    AlbumID INT AUTO_INCREMENT PRIMARY KEY,
    ArtistID INT NOT NULL,
    Titel VARCHAR(150) NOT NULL,
    Erscheinungsdatum DATE NOT NULL,
    Genre VARCHAR(50) NOT NULL,
    FOREIGN KEY (ArtistID) REFERENCES ARTIST(ArtistID) ON DELETE NO ACTION
);

CREATE TABLE TRACK (
    TrackID INT AUTO_INCREMENT PRIMARY KEY,
    AlbumID INT NOT NULL,
    Titel VARCHAR(100) NOT NULL,
    Dauer_Sekunden INT NOT NULL CHECK (Dauer_Sekunden > 0),
    FOREIGN KEY (AlbumID) REFERENCES ALBUM(AlbumID) ON DELETE CASCADE
);

CREATE TABLE TRACK_FEATURE (
    TrackID INT NOT NULL,
    ArtistID INT NOT NULL,
    PRIMARY KEY (TrackID, ArtistID),
    FOREIGN KEY (TrackID) REFERENCES TRACK(TrackID) ON DELETE CASCADE,
    FOREIGN KEY (ArtistID) REFERENCES ARTIST(ArtistID) ON DELETE CASCADE
);

CREATE TABLE STREAM_EREIGNIS (
    StreamID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    TrackID INT NOT NULL,
    Zeitstempel DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Geraet VARCHAR(100) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES USER(UserID) ON DELETE CASCADE,
    FOREIGN KEY (TrackID) REFERENCES TRACK(TrackID) ON DELETE CASCADE
);