/*Datenbank und Tabellen erstellen*/

CREATE DATABASE INF2025i_AppleMusicLight;
USE INF2025i_AppleMusicLight;

CREATE TABLE USER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Benutzername VARCHAR(20) NOT NULL UNIQUE,
    Emailadresse VARCHAR(100) NOT NULL UNIQUE,
    Registrierungsdatum DATE NOT NULL DEFAULT CURRENT_DATE,
    HatPremium BOOLEAN NOT NULL
);

CREATE TABLE RECORDLABEL (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    LandCode VARCHAR(2) NOT NULL DEFAULT 'CH'
);

CREATE TABLE ARTIST (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Kuenstlername VARCHAR(100) NOT NULL,
    Biografie TEXT,
    LabelID INT,
    CONSTRAINT FK_ARTIST_LABEL FOREIGN KEY (LabelID)
	 REFERENCES RECORDLABEL(ID) ON DELETE NO ACTION
);

CREATE TABLE ALBUM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Titel VARCHAR(100) NOT NULL,
    Erscheinungsdatum DATE NOT NULL,
    Genre VARCHAR(50) NOT NULL,
    ArtistID INT NOT NULL,
    CONSTRAINT FK_ALBUM_ARTIST FOREIGN KEY (ArtistID)
	 REFERENCES ARTIST(ID) ON DELETE NO ACTION
);

CREATE TABLE TRACK (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Titel VARCHAR(100) NOT NULL,
    Dauer_Sekunden INT NOT NULL CHECK (Dauer_Sekunden > 0),
    AlbumID INT NOT NULL,
    CONSTRAINT FK_TRACK_ALBUM FOREIGN KEY (AlbumID)
	 REFERENCES ALBUM(ID) ON DELETE CASCADE
);

CREATE TABLE STREAM_EREIGNIS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Zeitstempel DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Geraet VARCHAR(100) NOT NULL,
    UserID INT NOT NULL,
    TrackID INT NOT NULL,
    CONSTRAINT FK_STREAM_EREIGNIS_USER FOREIGN KEY (UserID)
	 REFERENCES USER(ID) ON DELETE CASCADE,
	 CONSTRAINT FK_STREAM_EREIGNIS_TRACK FOREIGN KEY (TrackID)
	 REFERENCES TRACK(ID) ON DELETE CASCADE
);

CREATE TABLE TRACK_FEATURE (
    TrackID INT NOT NULL,
    ArtistID INT NOT NULL,
    CONSTRAINT FK_TRACK_FEATURE_TRACK FOREIGN KEY (TrackID)
	 REFERENCES TRACK(ID) ON DELETE CASCADE,
	 CONSTRAINT FK_TRACK_FEATURE_ARTIST FOREIGN KEY (ArtistID)
	 REFERENCES ARTIST(ID) ON DELETE CASCADE
);